// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue-beats: https://github.com/elastic/beats/issues/
:pull-beats: https://github.com/elastic/beats/pull/

:issue: https://github.com/elastic/elastic-agent/issues/
:pull: https://github.com/elastic/elastic-agent/pull/

=== Elastic Agent version HEAD

==== Breaking changes

- Docker container is not run as root by default. {pull-beats}[21213]
- Read Fleet connection information from `fleet.*` instead of `fleet.kibana.*`. {pull-beats}[24713]
- Beats build for 32Bit Windows or Linux system will refuse to run on a 64bit system. {pull-beats}[25186]
- Remove the `--kibana-url` from `install` and `enroll` command. {pull-beats}[25529]
- Default to port 80 and 443 for Kibana and Fleet Server connections. {pull-beats}[25723]
- Remove deprecated/undocumented IncludeCreatorMetadata setting from kubernetes metadata config options {pull-beats}[28006]
- The `/processes/<subprocess>` endpoint proxies to the subprocess's monitoring endpoint, instead of querying its `/stats` endpoint {pull-beats}[28165]
- Remove username/password for fleet-server authentication. {pull-beats}[29458]

==== Bugfixes
- Fix rename *ConfigChange to *PolicyChange to align on changes in the UI. {pull-beats}[20779]
- Thread safe sorted set {pull-beats}[21290]
- Copy Action store on upgrade {pull-beats}[21298]
- Include inputs in action store actions {pull-beats}[21298]
- Fix issue where inputs without processors defined would panic {pull-beats}[21628]
- Prevent reporting ecs version twice {pull-beats}[21616]
- Partial extracted beat result in failure to spawn beat {issue-beats}[21718]
- Use symlink path for reexecutions {pull-beats}[21835]
- Use ML_SYSTEM to detect if agent is running as a service {pull-beats}[21884]
- Use local temp instead of system one {pull-beats}[21883]
- Rename monitoring index from `elastic.agent` to `elastic_agent` {pull-beats}[21932]
- Fix issue with named pipes on Windows 7 {pull-beats}[21931]
- Fix missing elastic_agent event data {pull-beats}[21994]
- Ensure shell wrapper path exists before writing wrapper on install {pull-beats}[22144]
- Fix deb/rpm packaging for Elastic Agent {pull-beats}[22153]
- Fix composable input processor promotion to fix duplicates {pull-beats}[22344]
- Fix sysv init files for deb/rpm installation {pull-beats}[22543]
- Fix shell wrapper for deb/rpm packaging {pull-beats}[23038]
- Fixed parsing of npipe URI {pull-beats}[22978]
- Select default agent policy if no enrollment token provided. {pull-beats}[23973]
- Remove artifacts on transient download errors {pull-beats}[23235]
- Support for linux/arm64 {pull-beats}[23479]
- Skip top level files when unziping archive during upgrade {pull-beats}[23456]
- Do not take ownership of Endpoint log path {pull-beats}[23444]
- Fixed fetching DBus service PID {pull-beats}[23496]
- Fix issue of missing log messages from filebeat monitor {pull-beats}[23514]
- Increase checkin grace period to 30 seconds {pull-beats}[23568]
- Fix libbeat from reporting back degraded on config update {pull-beats}[23537]
- Rewrite check if agent is running with admin rights on Windows {pull-beats}[23970]
- Fix issues with dynamic inputs and conditions {pull-beats}[23886]
- Fix bad substitution of API key. {pull-beats}[24036]
- Fix docker enrollment issue related to Fleet Server change. {pull-beats}[24155]
- Improve log on failure of Endpoint Security installation. {pull-beats}[24429]
- Verify communication to Kibana before updating Fleet client. {pull-beats}[24489]
- Fix nil pointer when null is generated as list item. {issue-beats}[23734]
- Add support for filestream input. {pull-beats}[24820]
- Add check for URL set when cert and cert key. {pull-beats}[24904]
- Fix install command for Fleet Server bootstrap, remove need for --enrollment-token when using --fleet-server {pull-beats}[24981]
- Respect host configuration for exposed processes endpoint {pull-beats}[25114]
- Set --inscure in container when FLEET_SERVER_ENABLE and FLEET_INSECURE set {pull-beats}[25137]
- Fixed: limit for retries to Kibana configurable {issue-beats}[25063]
- Fix issue with status and inspect inside of container {pull-beats}[25204]
- Remove FLEET_SERVER_POLICY_NAME env variable as it was not used {pull-beats}[25149]
- Reduce log level for listener cleanup to debug {pull-beats}
- Passing in policy id to container command works {pull-beats}[25352]
- Reduce log level for listener cleanup to debug {pull-beats}[25274]
- Delay the restart of application when a status report of failure is given {pull-beats}[25339]
- Don't log when upgrade capability doesn't apply {pull-beats}[25386]
- Fixed issue when unversioned home is set and invoked watcher failing with ENOENT {issue-beats}[25371]
- Fixed Elastic Agent: expecting Dict and received *transpiler.Key for '0' {issue-beats}[24453]
- Fix AckBatch to do nothing when no actions passed {pull-beats}[25562]
- Add error log entry when listener creation fails {issue-beats}[23482]
- Handle case where policy doesn't contain Fleet connection information {pull-beats}[25707]
- Fix fleet-server.yml spec to not overwrite existing keys {pull-beats}[25741]
- Agent sends wrong log level to Endpoint {issue-beats}[25583]
- Fix startup with failing configuration {pull-beats}[26057]
- Change timestamp in elatic-agent-json.log to use UTC {issue-beats}[25391]
- Fix add support for Logstash output. {pull-beats}[24305]
- Do not log Elasticsearch configuration for monitoring output when running with debug. {pull-beats}[26583]
- Fix issue where proxy enrollment options broke enrollment command. {pull-beats}[26749]
- Remove symlink.prev from previously failed upgrade {pull-beats}[26785]
- Fix apm-server supported outputs not being in sync with supported output types. {pull-beats}[26885]
- Set permissions during installation {pull-beats}[26665]
- Disable monitoring during fleet-server bootstrapping. {pull-beats}[27222]
- Fix issue with atomic extract running in K8s {pull-beats}[27396]
- Fix issue with install directory in state path in K8s {pull-beats}[27396]
- Disable monitoring during fleet-server bootstrapping. {pull-beats}[27222]
- Change output.elasticsearch.proxy_disabled flag to output.elasticsearch.proxy_disable so fleet uses it. {issue-beats}[27670] {pull-beats}[27671]
- Add validation for certificate flags to ensure they are absolute paths. {pull-beats}[27779]
- Migrate state on upgrade {pull-beats}[27825]
- Add "_monitoring" suffix to monitoring instance names to remove ambiguity with the status command. {issue-beats}[25449]
- Ignore ErrNotExists when fixing permissions. {issue-beats}[27836] {pull-beats}[27846]
- Snapshot artifact lookup will use agent.download proxy settings. {issue-beats}[27903] {pull-beats}[27904]
- Fix lazy acker to only add new actions to the batch. {pull-beats}[27981]
- Allow HTTP metrics to run in bootstrap mode. Add ability to adjust timeouts for Fleet Server. {pull-beats}[28260]
- Fix agent configuration overwritten by default fleet config. {pull-beats}[29297]
- Allow agent containers to use basic auth to create a service token. {pull-beats}[29651]
- Fix issue where a failing artifact verification does not remove the bad artifact. {pull-beats}[30281]
- Reduce Elastic Agent shut down time by stopping processes concurrently {pull-beats}[29650]
- Move `context cancelled` error from fleet gateway into debug level. {pull}187[187]
- Update library containerd to 1.5.10. {pull}186[186]
- Add fleet-server to output of elastic-agent inspect output command (and diagnostic bundle). {pull}243[243]
- Update API calls that the agent makes to Kibana when running the container command. {pull}253[253]
- diagnostics collect log names are fixed on Windows machines, command will ignore failures. AgentID is included in diagnostics(and diagnostics collect) output. {issue}81[81] {issue}92[92] {issue}190[190] {pull}262[262]
- Collects stdout and stderr of applications run as a process and logs them. {issue}[88]
- Remove VerificationMode option to empty string. Default value is `full`. {issue}[184]
- diagnostics collect file mod times are set. {pull}570[570]
- Allow ':' characters in dynamic variables {issue}624[624] {pull}680[680]
- Allow the - char to appear as part of variable names in eql expressions. {issue}709[709] {pull}710[710]
- Allow the / char in variable names in eql and transpiler. {issue}715[715] {pull}718[718]
- Fix data duplication for standalone agent on Kubernetes using the default manifest {issue-beats}31512[31512] {pull}742[742]
- Agent updates will clean up unneeded artifacts. {issue}693[693] {issue}694[694] {pull}752[752]
- Use the Elastic Agent configuration directory as the root of the `inputs.d` folder. {issues}663[663]
- Fix a panic caused by a race condition when installing the Elastic Agent. {issues}806[806]
- Remove fleet event reporter and events from checkin body. {issue}993[993]

==== New features

- Prepare packaging for endpoint and asc files {pull-beats}[20186]
- Improved version CLI {pull-beats}[20359]
- Enroll CLI now restarts running daemon {pull-beats}[20359]
- Add restart CLI cmd {pull-beats}[20359]
- Add new `synthetics/*` inputs to run Heartbeat {pull-beats}[20387]
- Users of the Docker image can now pass `FLEET_ENROLL_INSECURE=1` to include the `--insecure` flag with the `elastic-agent enroll` command {issue-beats}[20312] {pull-beats}[20713]
- Add `docker` composable dynamic provider. {pull-beats}[20842]
- Add support for dynamic inputs with providers and `{{variable|"default"}}` substitution. {pull-beats}[20839]
- Add support for EQL based condition on inputs {pull-beats}[20994]
- Send `fleet.host.id` to Endpoint Security {pull-beats}[21042]
- Add `install` and `uninstall` subcommands {pull-beats}[21206]
- Use new form of fleet API paths {pull-beats}[21478]
- Add `kubernetes` composable dynamic provider. {pull-beats}[21480]
- Send updating state {pull-beats}[21461]
- Add `elastic.agent.id` and `elastic.agent.version` to published events from filebeat and metricbeat {pull-beats}[21543]
- Add `upgrade` subcommand to perform upgrade of installed Elastic Agent {pull-beats}[21425]
- Update `fleet.yml` and Kibana hosts when a policy change updates the Kibana hosts {pull-beats}[21599]
- Update `install` command to perform enroll before starting Elastic Agent {pull-beats}[21772]
- Update `fleet.kibana.path` from a POLICY_CHANGE {pull-beats}[21804]
- Removed `install-service.ps1` and `uninstall-service.ps1` from Windows .zip packaging {pull-beats}[21694]
- Add `priority` to `AddOrUpdate` on dynamic composable input providers communication channel {pull-beats}[22352]
- Ship `endpoint-security` logs to elasticsearch {pull-beats}[22526]
- Log level reloadable from fleet {pull-beats}[22690]
- Push log level downstream {pull-beats}[22815]
- Add metrics collection for Agent {pull-beats}[22793]
- Add support for Fleet Server {pull-beats}[23736]
- Add support for enrollment with local bootstrap of Fleet Server {pull-beats}[23865]
- Add TLS support for Fleet Server {pull-beats}[24142]
- Add support for Fleet Server running under Elastic Agent {pull-beats}[24220]
- Add CA support to Elastic Agent docker image {pull-beats}[24486]
- Add k8s secrets provider for Agent {pull-beats}[24789]
- Add STATE_PATH, CONFIG_PATH, LOGS_PATH to Elastic Agent docker image {pull-beats}[24817]
- Add status subcommand {pull-beats}[24856]
- Add leader_election provider for k8s {pull-beats}[24267]
- Add --fleet-server-service-token and FLEET_SERVER_SERVICE_TOKEN options {pull-beats}[25083]
- Keep http and logging config during enroll {pull-beats}[25132]
- Log output of container to $LOGS_PATH/elastic-agent-start.log when LOGS_PATH set {pull-beats}[25150]
- Use `filestream` input for internal log collection. {pull-beats}[25660]
- Enable agent to send custom headers to kibana/ES {pull-beats}[26275]
- Set `agent.id` to the Fleet Agent ID in events published from inputs backed by Beats. {issue-beats}[21121] {pull-beats}[26394] {pull-beats}[26548]
- Add proxy support to artifact downloader and communication with fleet server. {pull-beats}[25219]
- Add proxy support to enroll command. {pull-beats}[26514]
- Enable configuring monitoring namespace {issue-beats}[26439]
- Communicate with Fleet Server over HTTP2. {pull-beats}[26474]
- Pass logging.metrics.enabled to beats to stop beats from adding metrics into their logs. {issue-beats}[26758] {pull-beats}[26828]
- Support Node and Service autodiscovery in kubernetes dynamic provider. {pull-beats}[26801]
- Increase Agent's mem limits in k8s. {pull-beats}[27153]
- Add new --enroll-delay option for install and enroll commands. {pull-beats}[27118]
- Add link to troubleshooting guide on fatal exits. {issue-beats}[26367] {pull-beats}[27236]
- Agent now adapts the beats queue size based on output settings. {issue-beats}[26638] {pull-beats}[27429]
- Support ephemeral containers in Kubernetes dynamic provider. {issue-beats}[#27020] {pull-beats}[27707]
- Add complete k8s metadata through composable provider. {pull-beats}[27691]
- Add diagnostics command to gather beat metadata. {pull-beats}[28265]
- Add diagnostics collect command to gather beat metadata, config, policy, and logs and bundle it into an archive. {pull-beats}[28461]
- Add `KIBANA_FLEET_SERVICE_TOKEN` to Elastic Agent container. {pull-beats}[28096]
- Enable pprof endpoints for beats processes. Allow pprof endpoints for elastic-agent if enabled. {pull-beats}[28983]
- Add `--pprof` flag to `elastic-agent diagnostics` and an `elastic-agent pprof` command to allow operators to gather pprof data from the agent and beats running under it. {pull-beats}[28798]
- Allow pprof endpoints for elastic-agent or beats if enabled. {pull-beats}[28983] {pull-beats}[29155]
- Add --fleet-server-es-ca-trusted-fingerprint flag to allow agent/fleet-server to work with elasticsearch clusters using self signed certs. {pull-beats}[29128]
- Discover changes in Kubernetes nodes metadata as soon as they happen. {pull-beats}[23139]
- Add results of inspect output command into archive produced by diagnostics collect. {pull-beats}[29902]
- Add support for loading input configuration from external configuration files in standalone mode. You can load inputs from YAML configuration files under the folder `{path.config}/inputs.d`. {pull-beats}[30087]
- Install command will skip install/uninstall steps when installation via package is detected on Linux distros. {pull-beats}[30289]
- Update docker/distribution dependency library to fix a security issues concerning OCI Manifest Type Confusion Issue. {pull-beats}[30462]
- Add action_input_type for the .fleet-actions-results {pull-beats}[30562]
- Add support for enabling the metrics buffer endpoint in the elastic-agent and beats it runs. diagnostics collect command will gather metrics-buffer data if enabled. {pull-beats}[30471]
- Update ack response schema and processing, add retrier for acks {pull}200[200]
- Enhance error messages and logs for process start {pull}225[225]
- Changed the default policy selection logic. When the agent has no policy id or name defined, it will fall back to defaults (defined by $FLEET_SERVER_POLICY_ID and $FLEET_DEFAULT_TOKEN_POLICY_NAME environment variables respectively). {issue-beats}[29774] {pull}226[226]
- Add Elastic APM instrumentation {pull}180[180]
- Agent can be built for `darwin/arm64`. When it's built for both `darwin/arm64` and `darwin/adm64` a universal binary is also built and packaged. {pull}203[203]
- Add support for Cloudbeat. {pull}179[179]
- Fix download verification in snapshot builds. {issue}252[252]
- Add support for kubernetes cronjobs {pull}279[279]
- Increase the download artifact timeout to 10mins and add log download statistics. {pull}308[308]
- Save the agent configuration and the state encrypted on the disk. {issue}535[535] {pull}398[398]
- Bump node.js version for heartbeat/synthetics to 16.15.0
- Support scheduled actions and cancellation of pending actions. {issue}393[393] {pull}419[419]
- Add `@metadata.input_id` and `@metadata.stream_id` when applying the inject stream processor {pull}527[527]
- Add liveness endpoint, allow fleet-gateway component to report degraded state, add update time and messages to status output. {issue}390[390] {pull}569[569]
- Redact sensitive information on diagnostics collect command. {issue}[241] {pull}[566]
- Fix incorrectly creating a filebeat redis input when a policy contains a packetbeat redis input. {issue}[427] {pull}[700]
- Add `lumberjack` input type to the Filebeat spec. {pull}[959]
