apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../default/elastic-agent-standalone
  - scc.yaml
  - scc-clusterrole.yaml
  - scc-rolebinding.yaml
  - scc-rolebinding-ksm.yaml
