# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  ASDF_MAGE_VERSION: 1.14.0

  # Make Docker builds less verbose
  BUILDKIT_PROGRESS: plain

  # The following images are defined here and their values will be updated by updatecli
  # Please do not change them manually.
  IMAGE_UBUNTU_2204_X86_64: "platform-ingest-elastic-agent-ubuntu-2204-1780275718"
  IMAGE_UBUNTU_2204_ARM_64: "platform-ingest-elastic-agent-ubuntu-2204-aarch64-1780275718"

# This section is used to define the plugins that will be used in the pipeline.
# See https://buildkite.com/docs/pipelines/integrations/plugins/using#using-yaml-anchors-with-plugins
common:
  - google_oidc_plugin: &google_oidc_plugin
      # See https://github.com/elastic/oblt-infra/blob/main/conf/resources/repos/elastic-agent/01-gcp-oidc.tf
      # This plugin authenticates to Google Cloud using the OIDC token.
      elastic/oblt-google-auth#v1.3.1:
        lifetime: 10800 # seconds
        project-id: "elastic-observability-ci"
        project-number: "911195782929"
  - vault_docker_login: &vault_docker_login
      elastic/vault-docker-login#v0.5.2:
        secret_path: 'kv/ci-shared/platform-ingest/elastic_docker_registry'
  - sparse_checkout_plugin: &sparse_checkout_plugin
      sparse-checkout#v1.6.0:
        paths:
        - .buildkite
        - .go-version
        - version/version.go

steps:
  - group: "Integration tests: packaging"
    key: "int-packaging"
    notify:
      - github_commit_status:
          context: "buildkite/elastic-agent - Packaging"
    steps:
      # Build matrix is not used for packaging in favor to unique step keys
      # Packaging amd64 non-containers
      - label: ":package: amd64: zip,tar.gz,rpm,deb "
        key: packaging-amd64
        env:
          PLATFORMS: "windows/amd64,linux/amd64"
          PACKAGES: "zip,tar.gz,rpm,deb"
        command: ".buildkite/scripts/steps/integration-package.sh"
        artifact_paths:
          - build/distributions/**
        retry:
          automatic:
            limit: 1
        agents:
          provider: "gcp"
          machineType: "n2-standard-8"
          image: "${IMAGE_UBUNTU_2204_X86_64}"
        plugins:
          - *google_oidc_plugin

      - label: ":package: amd64: FIPS tar.gz,zip (linux,windows)"
        key: "packaging-amd64-fips"
        env:
          PACKAGES: "tar.gz,zip"
          PLATFORMS: "linux/amd64,windows/amd64"
          FIPS: "true"
        command: ".buildkite/scripts/steps/integration-package.sh"
        artifact_paths:
          - build/distributions/**
        retry:
          automatic:
            limit: 1
        agents:
          provider: "gcp"
          machineType: "n2-standard-8"
          image: "${IMAGE_UBUNTU_2204_X86_64}"
        plugins:
          - *google_oidc_plugin

      # Packaging linux and windows for arm64
      - label: ":package: arm64: zip,tar.gz"
        key: packaging-arm64
        env:
          PLATFORMS: "windows/arm64,linux/arm64"
          PACKAGES: "tar.gz,zip"
        command: ".buildkite/scripts/steps/integration-package.sh"
        artifact_paths:
          - build/distributions/**
        retry:
          automatic:
            limit: 1
        agents:
          provider: "aws"
          instanceType: "c6g.2xlarge"
          image: "${IMAGE_UBUNTU_2204_ARM_64}"
        plugins:
          - *google_oidc_plugin

      - label: ":package: arm64: FIPS tar.gz,zip (linux,windows)"
        key: "packaging-arm64-fips"
        env:
          PACKAGES: "tar.gz,zip"
          PLATFORMS: "linux/arm64,windows/arm64"
          FIPS: "true"
        command: ".buildkite/scripts/steps/integration-package.sh"
        artifact_paths:
          - build/distributions/**
        retry:
          automatic:
            limit: 1
        agents:
          provider: "aws"
          instanceType: "c6g.2xlarge"
          image: "${IMAGE_UBUNTU_2204_ARM_64}"
        plugins:
          - *google_oidc_plugin

      - label: ":package: amd64: Containers"
        key: packaging-containers-amd64
        env:
          PACKAGES: "docker"
          PLATFORMS: "linux/amd64"
        command: |
          .buildkite/scripts/steps/integration-package.sh
          .buildkite/scripts/steps/integration-cloud-image-push.sh
        artifact_paths:
          - build/distributions/**
        agents:
          provider: "gcp"
          machineType: "n2-standard-8"
          diskSizeGb: 200
          image: "${IMAGE_UBUNTU_2204_X86_64}"
        plugins:
          - *google_oidc_plugin
          - *vault_docker_login

      - label: ":package: arm64: Containers"
        key: packaging-containers-arm64
        env:
          PACKAGES: "docker"
          PLATFORMS: "linux/arm64"
        command: |
          .buildkite/scripts/steps/integration-package.sh
        artifact_paths:
          - build/distributions/**
        agents:
          provider: "aws"
          instanceType: "c6g.4xlarge"
          diskSizeGb: 200
          image: "${IMAGE_UBUNTU_2204_ARM_64}"
        plugins:
          - *google_oidc_plugin

      - label: ":package: amd64: FIPS Containers"
        key: packaging-containers-amd64-fips
        env:
          PACKAGES: "docker"
          PLATFORMS: "linux/amd64"
          FIPS: "true"
        command: |
          .buildkite/scripts/steps/integration-package.sh
          .buildkite/scripts/steps/integration-cloud-image-push.sh
        artifact_paths:
          - build/distributions/**
        agents:
          provider: "gcp"
          machineType: "n2-standard-8"
          diskSizeGb: 200
          image: "${IMAGE_UBUNTU_2204_X86_64}"
        plugins:
          - *vault_docker_login
          - *google_oidc_plugin

      - label: ":package: arm64: FIPS Containers"
        key: packaging-containers-arm64-fips
        env:
          PACKAGES: "docker"
          PLATFORMS: "linux/arm64"
          FIPS: "true"
        command: |
          .buildkite/scripts/steps/integration-package.sh
        artifact_paths:
          - build/distributions/**
        agents:
          provider: "aws"
          instanceType: "c6g.2xlarge"
          diskSizeGb: 200
          image: "${IMAGE_UBUNTU_2204_ARM_64}"
        plugins:
          - *google_oidc_plugin

  - label: "Triggering Integration tests"
    command: "buildkite-agent pipeline upload .buildkite/bk.integration.pipeline.yml"
    plugins:
    - *sparse_checkout_plugin

  ## PRs
  - label: "Triggering custom FIPS integration tests"
    if: build.pull_request.id != null
    key: "fips-its-prs"
    command: "buildkite-agent pipeline upload .buildkite/bk.integration-fips.pipeline.yml"
    plugins:
    - *sparse_checkout_plugin
    if_changed:
      include:
        - .buildkite/**
        - magefile.go
        - dev-tools/**
        - "go.{mod,sum}"

  ## Branches
  - label: "Triggering custom FIPS integration tests (branches)"
    if: build.pull_request.id == null
    key: "fips-its-branches"
    command: "buildkite-agent pipeline upload .buildkite/bk.integration-fips.pipeline.yml"
    plugins:
    - *sparse_checkout_plugin

  - label: "Test packages"
    depends_on:
    - int-packaging
    command: |
      .buildkite/scripts/steps/package-tests.sh
    agents:
      provider: "gcp"
      machineType: "n2-standard-8"
      diskSizeGb: 200
      image: "${IMAGE_UBUNTU_2204_X86_64}"
