notify:
  - slack:
      channels:
        - "#ingest-notifications"
    if: (build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9x]+\$/) && (build.state == 'passed' || build.state == 'failed')
  - slack:
      channels:
        - "#ingest-notifications"
      message: |
        🚦 Pipeline waiting to be unblocked 🚦
        Repo: `${REPO}`

        New version: `${NEW_VERSION}`
        Branch: `${BRANCH}`
        Workflow: `${WORKFLOW}`
        ${BUILDKITE_BUILD_URL}
    if: build.state == "blocked"

steps:
  # TODO: replace steps with branch creation logic
  - block: "Placeholder blocked step"
    prompt: |
      Unblock when your team is ready to proceed.

      Trigger parameters:
      - NEW_VERSION: ${NEW_VERSION}
      - BRANCH: ${BRANCH}
      - WORKFLOW: ${WORKFLOW}
    key: block-get-dra-artifacts
    blocked_state: running

  - label: "Create branch for version bump"
    key: branch-for-version-bump
    depends_on: block-get-dra-artifacts
    agents:
      image: docker.elastic.co/release-eng/wolfi-build-essential-release-eng:latest
      cpu: 250m
      memory: 512Mi
      ephemeralStorage: 1Gi
    command:
      - echo "Placeholder"
