# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  VAULT_PATH: "kv/ci-shared/observability-ingest/cloud/gcp"

  # The following images are defined here and their values will be updated by updatecli
  # Please do not change them manually.
  IMAGE_UBUNTU_2204_X86_64: "platform-ingest-elastic-agent-ubuntu-2204-1776432347"
  IMAGE_UBUNTU_2204_ARM_64: "platform-ingest-elastic-agent-ubuntu-2204-aarch64-1776432347"
  IMAGE_WIN_2016: "platform-ingest-elastic-agent-windows-2016-1776432347"
  IMAGE_WIN_2022: "platform-ingest-elastic-agent-windows-2022-1776432347"
  #IMAGE_WIN_10: "platform-ingest-elastic-agent-windows-10-1776432347"
  #IMAGE_WIN_11: "platform-ingest-elastic-agent-windows-11-1776432347"
  IMAGE_WIN_10: "platform-ingest-elastic-agent-windows-10-pro"
  IMAGE_WIN_11: "platform-ingest-elastic-agent-windows-11-pro"

steps:

  - group: "Desktop Windows tests"
    key: "extended-windows"
    steps:
    steps:
      - label: "Unit tests - Windows 10 - {{matrix}}"
        command: .buildkite/scripts/steps/unit-tests.ps1
        agents:
          provider: "azure"
          image: "${IMAGE_WIN_10}"
          vm_size: "{{matrix}}"
        matrix:
          - "Standard_D2s_v6"
          - "Standard_D4s_v6"
          - "Standard_D8s_v6"
          - "Standard_D2s_v5"
          - "Standard_D4s_v5"
          - "Standard_D8s_v5"

      - label: "Unit tests - Windows 10 - {{matrix}} disk 256"
        command: .buildkite/scripts/steps/unit-tests.ps1
        agents:
          provider: "azure"
          image: "${IMAGE_WIN_10}"
          vmSize: "{{matrix}}"
          diskSizeGb: "256"
        matrix:
          - "Standard_D2s_v6"
          - "Standard_D4s_v6"
          - "Standard_D8s_v6"
          - "Standard_D2s_v5"
          - "Standard_D4s_v5"
          - "Standard_D8s_v5"
