// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License 2.0;
// you may not use this file except in compliance with the Elastic License 2.0.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fleet

import (
	mock "github.com/stretchr/testify/mock"

	"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade/ttl"
)

// newMockRollbacksSource creates a new instance of mockRollbacksSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRollbacksSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRollbacksSource {
	mock := &mockRollbacksSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockRollbacksSource is an autogenerated mock type for the rollbacksSource type
type mockRollbacksSource struct {
	mock.Mock
}

type mockRollbacksSource_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRollbacksSource) EXPECT() *mockRollbacksSource_Expecter {
	return &mockRollbacksSource_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type mockRollbacksSource
func (_mock *mockRollbacksSource) GetAll() (map[string]ttl.TTLMarker, map[string]error, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]ttl.TTLMarker
	var r1 map[string]error
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]ttl.TTLMarker, map[string]error, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]ttl.TTLMarker); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]ttl.TTLMarker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() map[string]error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]error)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockRollbacksSource_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type mockRollbacksSource_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *mockRollbacksSource_Expecter) GetAll() *mockRollbacksSource_GetAll_Call {
	return &mockRollbacksSource_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *mockRollbacksSource_GetAll_Call) Run(run func()) *mockRollbacksSource_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockRollbacksSource_GetAll_Call) Return(markers map[string]ttl.TTLMarker, malformed map[string]error, err error) *mockRollbacksSource_GetAll_Call {
	_c.Call.Return(markers, malformed, err)
	return _c
}

func (_c *mockRollbacksSource_GetAll_Call) RunAndReturn(run func() (map[string]ttl.TTLMarker, map[string]error, error)) *mockRollbacksSource_GetAll_Call {
	_c.Call.Return(run)
	return _c
}
