#!/usr/bin/env groovy

@Library('apm@feature/use-internal-ci') _

pipeline {
  agent { label 'ubuntu-20.04 && immutable' }
  environment {
    FOLDER_NAME = 'elastic-agent'
    REPO = "elastic-agent-poc"
    BASE_DIR = "src/github.com/elastic/${env.REPO}"
    JOB_GIT_CREDENTIALS = "f6c7695a-671e-4f4f-a331-acdce44ff9ba"
    PIPELINE_LOG_LEVEL = 'INFO'
  }
  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20', daysToKeepStr: '30'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    rateLimitBuilds(throttle: [count: 60, durationName: 'hour', userBoost: true])
    quietPeriod(10)
  }
  triggers {
    issueCommentTrigger("${obltGitHubComments()}")
  }
  stages {
    stage('Checkout') {
      steps {
        pipelineManager([ cancelPreviousRunningBuilds: [ when: 'PR' ] ])
        deleteDir()
        gitCheckout(basedir: "${BASE_DIR}", githubNotifyFirstTimeContributor: true)
        stash allowEmpty: true, name: 'source', useDefaultExcludes: false
      }
    }
    stage('Lint'){
      steps {
        withGithubNotify(context: "Lint") {
          withMageEnv(){
           dir("${BASE_DIR}/${FOLDER_NAME}"){
              cmd(label: 'check license, lint', script: 'mage check')
              cmd(label: 'update', script: 'mage update')
            }
            //dir("${BASE_DIR}"){
             // cmd(label: 'check no changes', script: 'mage checknochanges')
            //}
          }
        }
      }
    }
    stage('Test') {
      failFast false
      matrix {
        agent {label "${PLATFORM}"}
        options { skipDefaultCheckout() }
        axes {
          axis {
            name 'PLATFORM'
            values 'macosx && x86_64', 'ubuntu-20.04 && immutable', 'aarch64', 'windows-2019 && windows-immutable'
          }
        }
        stages {
          stage('build'){
            steps {
              withGithubNotify(context: "Build-${PLATFORM}") {
                deleteDir()
                unstash 'source'
                withMageEnv(){
                  dir("${BASE_DIR}/${FOLDER_NAME}"){
                    cmd(label: 'Go build', script: 'mage build')
                  }
                }
              }
            }
          }
          stage('Test') {
            steps {
              withGithubNotify(context: "Test-${PLATFORM}") {
                withMageEnv(){
                  dir("${BASE_DIR}/${FOLDER_NAME}"){
                    cmd(label: 'Go unitTest', script: 'mage unitTest')
                  }
                }
              }
            }
            post {
              always {
                junit(allowEmptyResults: true, keepLongStdio: true, testResults: "${BASE_DIR}/${FOLDER_NAME}/**/build/TEST*.xml")
              }
            }
          }
        }
      }
    }
    stage('Integration Test') {
      steps {
        withGithubNotify(context: "Integration Test") {
          deleteDir()
          unstash 'source'
          withMageEnv(){
            dir("${BASE_DIR}/${FOLDER_NAME}"){
              cmd(label: 'mage goIntegTest', script: 'mage goIntegTest')
            }
          }
        }
      }
      post {
        always {
          junit(allowEmptyResults: true, keepLongStdio: true, testResults: "${BASE_DIR}/${FOLDER_NAME}/**/build/TEST*.xml")
        }
      }
    }
  }
  post {
    cleanup {
      notifyBuildResult(prComment: true)
    }
  }
}
