// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License 2.0;
// you may not use this file except in compliance with the Elastic License 2.0.

// Code generated by dev-tools/cmd/buildfleetcfg/buildfleetcfg.go - DO NOT EDIT.

package application

import "github.com/elastic/elastic-agent/pkg/packer"

// DefaultAgentFleetConfig is the content of the default configuration when we enroll a beat, the elastic-agent.yml
// will be replaced with this variables.
var DefaultAgentFleetConfig []byte

func init() {
	// Packed File
	// _meta/elastic-agent.fleet.yml
	unpacked := packer.MustUnpack("eJycVU2Pq7rd3z8f4+yfWwLD9FDpLmIyGHMSTkNubOxNhe0MkNgJagLEVP3ulSFhZqrb6qqLbIj9f/m9+R/f/qYPt+JPB1Vcb7X4/6I8nG+/vKvD4faL0erbX74hswz++pvzx347EDPiK6GjK1r9wTsfvx/IgJCRyBEGNMKAI3d9XRC5EBqfUIxbBrFBb+zKCHbWIfC5ty+pG7UIZopp1bIduHEvdVCcKhlnDddyCOtNyc5Jx3fAKeC+3LmqpsSvUISTdQ3YXCPGPYORw8ZzakCQNRzuSwm/l9QNWqbVWeaJQnF2YTswsDxzCuKfhbHnI8f2ofZ/6HcyBIPMQc+9xGFkW9Lzqcz0XbF824Z6mv9neSkRxC0lyZWR7SuKMyPJ/sdYh0jFz9uWwcDj+t5Rsn2131G4PCJo9w2MxcLW5lANMgQdq8HAPWyouy8xThJhgOYeKoXGjtBKSYuPAQsBpaEkUwhGRkKlKUkd0V+OKFyWwg0WQqdKDJcfyCxtv3K9W9ZFnDki3ryuTVCJc9YwHR1lvGkZuVfCyxpq/CM3wYl7suUwqFi86VA51UTh8obC5CLjrBfDpVu7rOLwXlOS/n2t8Qsli57DffexazasDXr038wz2Z3QyMtb+QmX+X8EWSdqUPH693dc1+DEcmAYSSsJ8QnBxEdx2sk8ObJ8c0WxvBQkvSAYuCxPTEEyNXGrBhSzisdYIag0gkknYTlxHQPD8tRyNc37rIfxbvfbpUS6cmQMhp/1947miVMQVlEvG9YaX2meOgXZtNT9/p93h5FThMDhZtIug8rO73Av8RFMO37OqoL4DdfiEyaZYiHoLb5WR09uJYwMc7GTu1kjND5KGJiDnbHO/jz18U80z6r33Rce61l31k8EdzLflkwHBsGsk65/5W50sj5AMaioe6uYu39gMZ9/Ras3s4k3814F8QcJoyuPgp7m2cX6V7ipKUjywHxfchgcaZ413H0puUs/7lju5l54WHvAcNfyvRjWNUhkOGZHxeO0QzEeGNnOfce540RRko2YiTjpmJdUfAcGAfGxIKyhbuQUJGiFeZnuQdUKL7OafR9xWv0uZg0/pw4l9ysqrXeAna2Vod8LHRxZng4/n34w4DZyRqIrikEnztuSn/GNamweGh4EjDw+Zp7dLVXCS2ceOVFt7o33LK79ZrXsP7JhUR2guknilAIGRoaglWRRsxw9dk97msvW5obdnbp4EC4epvvgRvPqfby3upSbYWlrz9hJqG6MBAsZTrlCvUSN/GhRco29L7Oal1K6leI1mPefvPvIRpKO39gZX3l8etayuq0Pz/z90M+HH7ysGvHygH1jRp6mutYLafPMRLoDmhJ1tXn92G3CVAVOQRaKe9j5WS8Hq8nPeTtm5fn0KWvnfC4ZxA7LE8ud1ahXQOwU9j2KEyVj60c7M+iElzZU39W6Bm+MsEqSuzPNaDMkVeuHDhjxK3uOrS6ljJMF2876MCzPTEHwkLtpJ4lv37OekbRhWtneM6fWF898t5hnEGua4+vkgeWw/tDcztY87MCRe1aX9r1Y3hFcKEp8y42DYtlw2JdU7+eaLAQd1/uJ+x2o2DlTop6+MR01PMaG7R4+mXBoWJ6+UzdY8FGfH55n0GbeqRQeUNRV2u5nfc9hZLFrEVwMCNoaUjHy8l/3mrPkcf/J5bMXJ9FL7j5qf8XOarzhOb79z71X4ItfHnu9ohW+zbp5wy8CBi0jvlNYn8NMSYiN9S7LN6M3JKwslif7hh52Y2Y5QuPH2xQNCH6t8YnLvLCZudr0wsz3K6635eaTdkZMwr5Mj8vrv+fv152sV+7DU38sr3ru+oqfs4aS/vWp27D89ddv//y/fwUAAP//3ax4tQ==")
	raw, ok := unpacked["_meta/elastic-agent.fleet.yml"]
	if !ok {
		// ensure we have something loaded.
		panic("elastic-agent.fleet.yml is not included in the binary")
	}
	DefaultAgentFleetConfig = raw
}
