// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by mockery v2.20.0. DO NOT EDIT.

// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

package mocks

import (
	config "github.com/elastic/elastic-agent/internal/pkg/config"
	component "github.com/elastic/elastic-agent/pkg/component"

	mock "github.com/stretchr/testify/mock"
)

// MonitorManager is an autogenerated mock type for the MonitorManager type
type MonitorManager struct {
	mock.Mock
}

type MonitorManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MonitorManager) EXPECT() *MonitorManager_Expecter {
	return &MonitorManager_Expecter{mock: &_m.Mock}
}

// Enabled provides a mock function with given fields:
func (_m *MonitorManager) Enabled() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MonitorManager_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type MonitorManager_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
func (_e *MonitorManager_Expecter) Enabled() *MonitorManager_Enabled_Call {
	return &MonitorManager_Enabled_Call{Call: _e.mock.On("Enabled")}
}

func (_c *MonitorManager_Enabled_Call) Run(run func()) *MonitorManager_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MonitorManager_Enabled_Call) Return(_a0 bool) *MonitorManager_Enabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MonitorManager_Enabled_Call) RunAndReturn(run func() bool) *MonitorManager_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// MonitoringConfig provides a mock function with given fields: _a0, _a1, _a2
func (_m *MonitorManager) MonitoringConfig(_a0 map[string]interface{}, _a1 []component.Component, _a2 map[string]string) (map[string]interface{}, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, []component.Component, map[string]string) (map[string]interface{}, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}, []component.Component, map[string]string) map[string]interface{}); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}, []component.Component, map[string]string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MonitorManager_MonitoringConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MonitoringConfig'
type MonitorManager_MonitoringConfig_Call struct {
	*mock.Call
}

// MonitoringConfig is a helper method to define mock.On call
//   - _a0 map[string]interface{}
//   - _a1 []component.Component
//   - _a2 map[string]string
func (_e *MonitorManager_Expecter) MonitoringConfig(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MonitorManager_MonitoringConfig_Call {
	return &MonitorManager_MonitoringConfig_Call{Call: _e.mock.On("MonitoringConfig", _a0, _a1, _a2)}
}

func (_c *MonitorManager_MonitoringConfig_Call) Run(run func(_a0 map[string]interface{}, _a1 []component.Component, _a2 map[string]string)) *MonitorManager_MonitoringConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]interface{}), args[1].([]component.Component), args[2].(map[string]string))
	})
	return _c
}

func (_c *MonitorManager_MonitoringConfig_Call) Return(_a0 map[string]interface{}, _a1 error) *MonitorManager_MonitoringConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MonitorManager_MonitoringConfig_Call) RunAndReturn(run func(map[string]interface{}, []component.Component, map[string]string) (map[string]interface{}, error)) *MonitorManager_MonitoringConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Reload provides a mock function with given fields: rawConfig
func (_m *MonitorManager) Reload(rawConfig *config.Config) error {
	ret := _m.Called(rawConfig)

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.Config) error); ok {
		r0 = rf(rawConfig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MonitorManager_Reload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reload'
type MonitorManager_Reload_Call struct {
	*mock.Call
}

// Reload is a helper method to define mock.On call
//   - rawConfig *config.Config
func (_e *MonitorManager_Expecter) Reload(rawConfig interface{}) *MonitorManager_Reload_Call {
	return &MonitorManager_Reload_Call{Call: _e.mock.On("Reload", rawConfig)}
}

func (_c *MonitorManager_Reload_Call) Run(run func(rawConfig *config.Config)) *MonitorManager_Reload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.Config))
	})
	return _c
}

func (_c *MonitorManager_Reload_Call) Return(_a0 error) *MonitorManager_Reload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MonitorManager_Reload_Call) RunAndReturn(run func(*config.Config) error) *MonitorManager_Reload_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMonitorManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewMonitorManager creates a new instance of MonitorManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMonitorManager(t mockConstructorTestingTNewMonitorManager) *MonitorManager {
	mock := &MonitorManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
