// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by mockery v2.20.0. DO NOT EDIT.

// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	reexec "github.com/elastic/elastic-agent/internal/pkg/agent/application/reexec"
)

// ReExecManager is an autogenerated mock type for the ReExecManager type
type ReExecManager struct {
	mock.Mock
}

type ReExecManager_Expecter struct {
	mock *mock.Mock
}

func (_m *ReExecManager) EXPECT() *ReExecManager_Expecter {
	return &ReExecManager_Expecter{mock: &_m.Mock}
}

// ReExec provides a mock function with given fields: callback, argOverrides
func (_m *ReExecManager) ReExec(callback reexec.ShutdownCallbackFn, argOverrides ...string) {
	_va := make([]interface{}, len(argOverrides))
	for _i := range argOverrides {
		_va[_i] = argOverrides[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, callback)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// ReExecManager_ReExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReExec'
type ReExecManager_ReExec_Call struct {
	*mock.Call
}

// ReExec is a helper method to define mock.On call
//   - callback reexec.ShutdownCallbackFn
//   - argOverrides ...string
func (_e *ReExecManager_Expecter) ReExec(callback interface{}, argOverrides ...interface{}) *ReExecManager_ReExec_Call {
	return &ReExecManager_ReExec_Call{Call: _e.mock.On("ReExec",
		append([]interface{}{callback}, argOverrides...)...)}
}

func (_c *ReExecManager_ReExec_Call) Run(run func(callback reexec.ShutdownCallbackFn, argOverrides ...string)) *ReExecManager_ReExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(reexec.ShutdownCallbackFn), variadicArgs...)
	})
	return _c
}

func (_c *ReExecManager_ReExec_Call) Return() *ReExecManager_ReExec_Call {
	_c.Call.Return()
	return _c
}

func (_c *ReExecManager_ReExec_Call) RunAndReturn(run func(reexec.ShutdownCallbackFn, ...string)) *ReExecManager_ReExec_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewReExecManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewReExecManager creates a new instance of ReExecManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReExecManager(t mockConstructorTestingTNewReExecManager) *ReExecManager {
	mock := &ReExecManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
