// Code generated by mockery v2.20.0. DO NOT EDIT.

// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

type Runner_Expecter struct {
	mock *mock.Mock
}

func (_m *Runner) EXPECT() *Runner_Expecter {
	return &Runner_Expecter{mock: &_m.Mock}
}

// Errors provides a mock function with given fields:
func (_m *Runner) Errors() <-chan error {
	ret := _m.Called()

	var r0 <-chan error
	if rf, ok := ret.Get(0).(func() <-chan error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}

	return r0
}

// Runner_Errors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errors'
type Runner_Errors_Call struct {
	*mock.Call
}

// Errors is a helper method to define mock.On call
func (_e *Runner_Expecter) Errors() *Runner_Errors_Call {
	return &Runner_Errors_Call{Call: _e.mock.On("Errors")}
}

func (_c *Runner_Errors_Call) Run(run func()) *Runner_Errors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Runner_Errors_Call) Return(_a0 <-chan error) *Runner_Errors_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Runner_Errors_Call) RunAndReturn(run func() <-chan error) *Runner_Errors_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: _a0
func (_m *Runner) Run(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Runner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Runner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Runner_Expecter) Run(_a0 interface{}) *Runner_Run_Call {
	return &Runner_Run_Call{Call: _e.mock.On("Run", _a0)}
}

func (_c *Runner_Run_Call) Run(run func(_a0 context.Context)) *Runner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Runner_Run_Call) Return(_a0 error) *Runner_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Runner_Run_Call) RunAndReturn(run func(context.Context) error) *Runner_Run_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewRunner interface {
	mock.TestingT
	Cleanup(func())
}

// NewRunner creates a new instance of Runner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRunner(t mockConstructorTestingTNewRunner) *Runner {
	mock := &Runner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
