# docker build -t local.elastic.agent/elastic-agent:elastic-agent-8.6.0-SNAPSHOT .
FROM docker.elastic.co/beats/elastic-agent:8.6.0-SNAPSHOT

COPY ./elastic-agent.yml /usr/share/elastic-agent/elastic-agent.yml
