// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License 2.0;
// you may not use this file except in compliance with the Elastic License 2.0.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package info

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/elastic/elastic-agent/pkg/core/logger"
)

// NewMockAgent creates a new instance of MockAgent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgent {
	mock := &MockAgent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgent is an autogenerated mock type for the Agent type
type MockAgent struct {
	mock.Mock
}

type MockAgent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgent) EXPECT() *MockAgent_Expecter {
	return &MockAgent_Expecter{mock: &_m.Mock}
}

// ECSMetadata provides a mock function for the type MockAgent
func (_mock *MockAgent) ECSMetadata(v *logger.Logger) (*ECSMeta, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for ECSMetadata")
	}

	var r0 *ECSMeta
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*logger.Logger) (*ECSMeta, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(*logger.Logger) *ECSMeta); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ECSMeta)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*logger.Logger) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgent_ECSMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ECSMetadata'
type MockAgent_ECSMetadata_Call struct {
	*mock.Call
}

// ECSMetadata is a helper method to define mock.On call
//   - v *logger.Logger
func (_e *MockAgent_Expecter) ECSMetadata(v interface{}) *MockAgent_ECSMetadata_Call {
	return &MockAgent_ECSMetadata_Call{Call: _e.mock.On("ECSMetadata", v)}
}

func (_c *MockAgent_ECSMetadata_Call) Run(run func(v *logger.Logger)) *MockAgent_ECSMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *logger.Logger
		if args[0] != nil {
			arg0 = args[0].(*logger.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgent_ECSMetadata_Call) Return(eCSMeta *ECSMeta, err error) *MockAgent_ECSMetadata_Call {
	_c.Call.Return(eCSMeta, err)
	return _c
}

func (_c *MockAgent_ECSMetadata_Call) RunAndReturn(run func(v *logger.Logger) (*ECSMeta, error)) *MockAgent_ECSMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgentID provides a mock function for the type MockAgent
func (_mock *MockAgent) GetAgentID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAgentID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAgent_GetAgentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentID'
type MockAgent_GetAgentID_Call struct {
	*mock.Call
}

// GetAgentID is a helper method to define mock.On call
func (_e *MockAgent_Expecter) GetAgentID() *MockAgent_GetAgentID_Call {
	return &MockAgent_GetAgentID_Call{Call: _e.mock.On("GetAgentID")}
}

func (_c *MockAgent_GetAgentID_Call) Run(run func()) *MockAgent_GetAgentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_GetAgentID_Call) Return(s string) *MockAgent_GetAgentID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAgent_GetAgentID_Call) RunAndReturn(run func() string) *MockAgent_GetAgentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeaders provides a mock function for the type MockAgent
func (_mock *MockAgent) GetHeaders() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHeaders")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// MockAgent_GetHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeaders'
type MockAgent_GetHeaders_Call struct {
	*mock.Call
}

// GetHeaders is a helper method to define mock.On call
func (_e *MockAgent_Expecter) GetHeaders() *MockAgent_GetHeaders_Call {
	return &MockAgent_GetHeaders_Call{Call: _e.mock.On("GetHeaders")}
}

func (_c *MockAgent_GetHeaders_Call) Run(run func()) *MockAgent_GetHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_GetHeaders_Call) Return(stringToString map[string]string) *MockAgent_GetHeaders_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *MockAgent_GetHeaders_Call) RunAndReturn(run func() map[string]string) *MockAgent_GetHeaders_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogLevelOverride provides a mock function for the type MockAgent
func (_mock *MockAgent) GetLogLevelOverride() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogLevelOverride")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAgent_GetLogLevelOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogLevelOverride'
type MockAgent_GetLogLevelOverride_Call struct {
	*mock.Call
}

// GetLogLevelOverride is a helper method to define mock.On call
func (_e *MockAgent_Expecter) GetLogLevelOverride() *MockAgent_GetLogLevelOverride_Call {
	return &MockAgent_GetLogLevelOverride_Call{Call: _e.mock.On("GetLogLevelOverride")}
}

func (_c *MockAgent_GetLogLevelOverride_Call) Run(run func()) *MockAgent_GetLogLevelOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_GetLogLevelOverride_Call) Return(s string) *MockAgent_GetLogLevelOverride_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAgent_GetLogLevelOverride_Call) RunAndReturn(run func() string) *MockAgent_GetLogLevelOverride_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogLevelPolicy provides a mock function for the type MockAgent
func (_mock *MockAgent) GetLogLevelPolicy() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogLevelPolicy")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAgent_GetLogLevelPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogLevelPolicy'
type MockAgent_GetLogLevelPolicy_Call struct {
	*mock.Call
}

// GetLogLevelPolicy is a helper method to define mock.On call
func (_e *MockAgent_Expecter) GetLogLevelPolicy() *MockAgent_GetLogLevelPolicy_Call {
	return &MockAgent_GetLogLevelPolicy_Call{Call: _e.mock.On("GetLogLevelPolicy")}
}

func (_c *MockAgent_GetLogLevelPolicy_Call) Run(run func()) *MockAgent_GetLogLevelPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_GetLogLevelPolicy_Call) Return(s string) *MockAgent_GetLogLevelPolicy_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAgent_GetLogLevelPolicy_Call) RunAndReturn(run func() string) *MockAgent_GetLogLevelPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogLevelRuntime provides a mock function for the type MockAgent
func (_mock *MockAgent) GetLogLevelRuntime() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogLevelRuntime")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAgent_GetLogLevelRuntime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogLevelRuntime'
type MockAgent_GetLogLevelRuntime_Call struct {
	*mock.Call
}

// GetLogLevelRuntime is a helper method to define mock.On call
func (_e *MockAgent_Expecter) GetLogLevelRuntime() *MockAgent_GetLogLevelRuntime_Call {
	return &MockAgent_GetLogLevelRuntime_Call{Call: _e.mock.On("GetLogLevelRuntime")}
}

func (_c *MockAgent_GetLogLevelRuntime_Call) Run(run func()) *MockAgent_GetLogLevelRuntime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_GetLogLevelRuntime_Call) Return(s string) *MockAgent_GetLogLevelRuntime_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAgent_GetLogLevelRuntime_Call) RunAndReturn(run func() string) *MockAgent_GetLogLevelRuntime_Call {
	_c.Call.Return(run)
	return _c
}

// IsStandalone provides a mock function for the type MockAgent
func (_mock *MockAgent) IsStandalone() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStandalone")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAgent_IsStandalone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStandalone'
type MockAgent_IsStandalone_Call struct {
	*mock.Call
}

// IsStandalone is a helper method to define mock.On call
func (_e *MockAgent_Expecter) IsStandalone() *MockAgent_IsStandalone_Call {
	return &MockAgent_IsStandalone_Call{Call: _e.mock.On("IsStandalone")}
}

func (_c *MockAgent_IsStandalone_Call) Run(run func()) *MockAgent_IsStandalone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_IsStandalone_Call) Return(b bool) *MockAgent_IsStandalone_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAgent_IsStandalone_Call) RunAndReturn(run func() bool) *MockAgent_IsStandalone_Call {
	_c.Call.Return(run)
	return _c
}

// ReloadID provides a mock function for the type MockAgent
func (_mock *MockAgent) ReloadID(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReloadID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgent_ReloadID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReloadID'
type MockAgent_ReloadID_Call struct {
	*mock.Call
}

// ReloadID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgent_Expecter) ReloadID(ctx interface{}) *MockAgent_ReloadID_Call {
	return &MockAgent_ReloadID_Call{Call: _e.mock.On("ReloadID", ctx)}
}

func (_c *MockAgent_ReloadID_Call) Run(run func(ctx context.Context)) *MockAgent_ReloadID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgent_ReloadID_Call) Return(err error) *MockAgent_ReloadID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgent_ReloadID_Call) RunAndReturn(run func(ctx context.Context) error) *MockAgent_ReloadID_Call {
	_c.Call.Return(run)
	return _c
}

// SetLogLevelOverride provides a mock function for the type MockAgent
func (_mock *MockAgent) SetLogLevelOverride(level string) {
	_mock.Called(level)
	return
}

// MockAgent_SetLogLevelOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogLevelOverride'
type MockAgent_SetLogLevelOverride_Call struct {
	*mock.Call
}

// SetLogLevelOverride is a helper method to define mock.On call
//   - level string
func (_e *MockAgent_Expecter) SetLogLevelOverride(level interface{}) *MockAgent_SetLogLevelOverride_Call {
	return &MockAgent_SetLogLevelOverride_Call{Call: _e.mock.On("SetLogLevelOverride", level)}
}

func (_c *MockAgent_SetLogLevelOverride_Call) Run(run func(level string)) *MockAgent_SetLogLevelOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgent_SetLogLevelOverride_Call) Return() *MockAgent_SetLogLevelOverride_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAgent_SetLogLevelOverride_Call) RunAndReturn(run func(level string)) *MockAgent_SetLogLevelOverride_Call {
	_c.Run(run)
	return _c
}

// SetLogLevelPolicy provides a mock function for the type MockAgent
func (_mock *MockAgent) SetLogLevelPolicy(level string) {
	_mock.Called(level)
	return
}

// MockAgent_SetLogLevelPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogLevelPolicy'
type MockAgent_SetLogLevelPolicy_Call struct {
	*mock.Call
}

// SetLogLevelPolicy is a helper method to define mock.On call
//   - level string
func (_e *MockAgent_Expecter) SetLogLevelPolicy(level interface{}) *MockAgent_SetLogLevelPolicy_Call {
	return &MockAgent_SetLogLevelPolicy_Call{Call: _e.mock.On("SetLogLevelPolicy", level)}
}

func (_c *MockAgent_SetLogLevelPolicy_Call) Run(run func(level string)) *MockAgent_SetLogLevelPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgent_SetLogLevelPolicy_Call) Return() *MockAgent_SetLogLevelPolicy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAgent_SetLogLevelPolicy_Call) RunAndReturn(run func(level string)) *MockAgent_SetLogLevelPolicy_Call {
	_c.Run(run)
	return _c
}

// Snapshot provides a mock function for the type MockAgent
func (_mock *MockAgent) Snapshot() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAgent_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockAgent_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *MockAgent_Expecter) Snapshot() *MockAgent_Snapshot_Call {
	return &MockAgent_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *MockAgent_Snapshot_Call) Run(run func()) *MockAgent_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_Snapshot_Call) Return(b bool) *MockAgent_Snapshot_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAgent_Snapshot_Call) RunAndReturn(run func() bool) *MockAgent_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// Unprivileged provides a mock function for the type MockAgent
func (_mock *MockAgent) Unprivileged() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unprivileged")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAgent_Unprivileged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unprivileged'
type MockAgent_Unprivileged_Call struct {
	*mock.Call
}

// Unprivileged is a helper method to define mock.On call
func (_e *MockAgent_Expecter) Unprivileged() *MockAgent_Unprivileged_Call {
	return &MockAgent_Unprivileged_Call{Call: _e.mock.On("Unprivileged")}
}

func (_c *MockAgent_Unprivileged_Call) Run(run func()) *MockAgent_Unprivileged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_Unprivileged_Call) Return(b bool) *MockAgent_Unprivileged_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAgent_Unprivileged_Call) RunAndReturn(run func() bool) *MockAgent_Unprivileged_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MockAgent
func (_mock *MockAgent) Version() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAgent_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockAgent_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockAgent_Expecter) Version() *MockAgent_Version_Call {
	return &MockAgent_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockAgent_Version_Call) Run(run func()) *MockAgent_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_Version_Call) Return(s string) *MockAgent_Version_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAgent_Version_Call) RunAndReturn(run func() string) *MockAgent_Version_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentInfoStore creates a new instance of MockAgentInfoStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentInfoStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentInfoStore {
	mock := &MockAgentInfoStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentInfoStore is an autogenerated mock type for the AgentInfoStore type
type MockAgentInfoStore struct {
	mock.Mock
}

type MockAgentInfoStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentInfoStore) EXPECT() *MockAgentInfoStore_Expecter {
	return &MockAgentInfoStore_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockAgentInfoStore
func (_mock *MockAgentInfoStore) Load(ctx context.Context) (*AgentInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *AgentInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*AgentInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *AgentInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AgentInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentInfoStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockAgentInfoStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgentInfoStore_Expecter) Load(ctx interface{}) *MockAgentInfoStore_Load_Call {
	return &MockAgentInfoStore_Load_Call{Call: _e.mock.On("Load", ctx)}
}

func (_c *MockAgentInfoStore_Load_Call) Run(run func(ctx context.Context)) *MockAgentInfoStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentInfoStore_Load_Call) Return(agentInfo *AgentInfo, err error) *MockAgentInfoStore_Load_Call {
	_c.Call.Return(agentInfo, err)
	return _c
}

func (_c *MockAgentInfoStore_Load_Call) RunAndReturn(run func(ctx context.Context) (*AgentInfo, error)) *MockAgentInfoStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAgentInfoStore
func (_mock *MockAgentInfoStore) Save(ctx context.Context, opts ...SaveOption) error {
	// SaveOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...SaveOption) error); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentInfoStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAgentInfoStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...SaveOption
func (_e *MockAgentInfoStore_Expecter) Save(ctx interface{}, opts ...interface{}) *MockAgentInfoStore_Save_Call {
	return &MockAgentInfoStore_Save_Call{Call: _e.mock.On("Save",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockAgentInfoStore_Save_Call) Run(run func(ctx context.Context, opts ...SaveOption)) *MockAgentInfoStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []SaveOption
		variadicArgs := make([]SaveOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(SaveOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAgentInfoStore_Save_Call) Return(err error) *MockAgentInfoStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentInfoStore_Save_Call) RunAndReturn(run func(ctx context.Context, opts ...SaveOption) error) *MockAgentInfoStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
