// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License 2.0;
// you may not use this file except in compliance with the Elastic License 2.0.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ttl

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockReadOnlySource creates a new instance of MockReadOnlySource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadOnlySource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadOnlySource {
	mock := &MockReadOnlySource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReadOnlySource is an autogenerated mock type for the ReadOnlySource type
type MockReadOnlySource struct {
	mock.Mock
}

type MockReadOnlySource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadOnlySource) EXPECT() *MockReadOnlySource_Expecter {
	return &MockReadOnlySource_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockReadOnlySource
func (_mock *MockReadOnlySource) GetAll() (map[string]TTLMarker, map[string]error, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]TTLMarker
	var r1 map[string]error
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]TTLMarker, map[string]error, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]TTLMarker); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]TTLMarker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() map[string]error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]error)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockReadOnlySource_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockReadOnlySource_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockReadOnlySource_Expecter) GetAll() *MockReadOnlySource_GetAll_Call {
	return &MockReadOnlySource_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockReadOnlySource_GetAll_Call) Run(run func()) *MockReadOnlySource_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReadOnlySource_GetAll_Call) Return(stringToTTLMarker map[string]TTLMarker, stringToErr map[string]error, err error) *MockReadOnlySource_GetAll_Call {
	_c.Call.Return(stringToTTLMarker, stringToErr, err)
	return _c
}

func (_c *MockReadOnlySource_GetAll_Call) RunAndReturn(run func() (map[string]TTLMarker, map[string]error, error)) *MockReadOnlySource_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockSource
func (_mock *MockSource) GetAll() (map[string]TTLMarker, map[string]error, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]TTLMarker
	var r1 map[string]error
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]TTLMarker, map[string]error, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]TTLMarker); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]TTLMarker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() map[string]error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]error)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSource_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockSource_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockSource_Expecter) GetAll() *MockSource_GetAll_Call {
	return &MockSource_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockSource_GetAll_Call) Run(run func()) *MockSource_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_GetAll_Call) Return(stringToTTLMarker map[string]TTLMarker, stringToErr map[string]error, err error) *MockSource_GetAll_Call {
	_c.Call.Return(stringToTTLMarker, stringToErr, err)
	return _c
}

func (_c *MockSource_GetAll_Call) RunAndReturn(run func() (map[string]TTLMarker, map[string]error, error)) *MockSource_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockSource
func (_mock *MockSource) Remove(versionedHome string) error {
	ret := _mock.Called(versionedHome)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(versionedHome)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSource_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockSource_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - versionedHome string
func (_e *MockSource_Expecter) Remove(versionedHome interface{}) *MockSource_Remove_Call {
	return &MockSource_Remove_Call{Call: _e.mock.On("Remove", versionedHome)}
}

func (_c *MockSource_Remove_Call) Run(run func(versionedHome string)) *MockSource_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSource_Remove_Call) Return(err error) *MockSource_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSource_Remove_Call) RunAndReturn(run func(versionedHome string) error) *MockSource_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockSource
func (_mock *MockSource) Set(m map[string]TTLMarker) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(map[string]TTLMarker) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSource_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockSource_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - m map[string]TTLMarker
func (_e *MockSource_Expecter) Set(m interface{}) *MockSource_Set_Call {
	return &MockSource_Set_Call{Call: _e.mock.On("Set", m)}
}

func (_c *MockSource_Set_Call) Run(run func(m map[string]TTLMarker)) *MockSource_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]TTLMarker
		if args[0] != nil {
			arg0 = args[0].(map[string]TTLMarker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSource_Set_Call) Return(err error) *MockSource_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSource_Set_Call) RunAndReturn(run func(m map[string]TTLMarker) error) *MockSource_Set_Call {
	_c.Call.Return(run)
	return _c
}
