kubernetes:
  enabled: false
cloudDefend:
  enabled: true
  policy_id: "6fc15307-6002-4cb7-8b1b-0ce899ca8b6e"
outputs:
  default:
    type: ESPlainAuthAPI
    url: "https://localhost:443"
    api_key: "api_key_example"
