# A diagram of example components managed by Agent.
# To regenerate the image after changing this file, run:
#   d2 components-example.d2 components-example.svg
# To live-edit this file with immediate regeneration of the diagram, run:
#   d2 --watch components-example.d2 components-example.svg

filebeat1: {
  input1 -> output
  input2 -> output
}

filebeat2: {
  input -> output
}

metricbeat: {
  input1 -> output
  input2 -> output
}

endpoint: {
  input -> output
}

filebeat1.output -> elasticsearch1
metricbeat.output -> elasticsearch1

filebeat2.output -> logstash

endpoint.output -> elasticsearch2
