# A diagram of example components managed by Agent with the shipper enabled.
# To regenerate the image after changing this file, run:
#   d2 components-shipper-example.d2 components-shipper-example.svg
# To live-edit this file with immediate regeneration of the diagram, run:
#   d2 --watch components-shipper-example.d2 components-shipper-example.svg
 
filebeat1: {
  input1 -> output
  input2 -> output
}

filebeat2: {
  input -> output
}

metricbeat: {
  input1 -> output
  input2 -> output
}

endpoint: {
  input -> output
}

shipper1: {
  input1 -> output
  input2 -> output
}

shipper2: {
  input -> output
}

shipper3: {
  input -> output
}

filebeat1.output -> shipper1.input1
metricbeat.output -> shipper1.input2
shipper1.output -> elasticsearch1

filebeat2.output -> shipper2.input
shipper2.output -> logstash

endpoint.output -> shipper3.input
shipper3.output -> elasticsearch2
