// Code generated by mockery v2.20.0. DO NOT EDIT.

// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

package coordinator

import (
	context "context"

	transpiler "github.com/elastic/elastic-agent/internal/pkg/agent/transpiler"
	mock "github.com/stretchr/testify/mock"
)

// MockVarsManager is an autogenerated mock type for the VarsManager type
type MockVarsManager struct {
	mock.Mock
}

type MockVarsManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVarsManager) EXPECT() *MockVarsManager_Expecter {
	return &MockVarsManager_Expecter{mock: &_m.Mock}
}

// Errors provides a mock function with given fields:
func (_m *MockVarsManager) Errors() <-chan error {
	ret := _m.Called()

	var r0 <-chan error
	if rf, ok := ret.Get(0).(func() <-chan error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}

	return r0
}

// MockVarsManager_Errors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errors'
type MockVarsManager_Errors_Call struct {
	*mock.Call
}

// Errors is a helper method to define mock.On call
func (_e *MockVarsManager_Expecter) Errors() *MockVarsManager_Errors_Call {
	return &MockVarsManager_Errors_Call{Call: _e.mock.On("Errors")}
}

func (_c *MockVarsManager_Errors_Call) Run(run func()) *MockVarsManager_Errors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVarsManager_Errors_Call) Return(_a0 <-chan error) *MockVarsManager_Errors_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVarsManager_Errors_Call) RunAndReturn(run func() <-chan error) *MockVarsManager_Errors_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: _a0
func (_m *MockVarsManager) Run(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVarsManager_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockVarsManager_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockVarsManager_Expecter) Run(_a0 interface{}) *MockVarsManager_Run_Call {
	return &MockVarsManager_Run_Call{Call: _e.mock.On("Run", _a0)}
}

func (_c *MockVarsManager_Run_Call) Run(run func(_a0 context.Context)) *MockVarsManager_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockVarsManager_Run_Call) Return(_a0 error) *MockVarsManager_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVarsManager_Run_Call) RunAndReturn(run func(context.Context) error) *MockVarsManager_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields:
func (_m *MockVarsManager) Watch() <-chan []*transpiler.Vars {
	ret := _m.Called()

	var r0 <-chan []*transpiler.Vars
	if rf, ok := ret.Get(0).(func() <-chan []*transpiler.Vars); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan []*transpiler.Vars)
		}
	}

	return r0
}

// MockVarsManager_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockVarsManager_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
func (_e *MockVarsManager_Expecter) Watch() *MockVarsManager_Watch_Call {
	return &MockVarsManager_Watch_Call{Call: _e.mock.On("Watch")}
}

func (_c *MockVarsManager_Watch_Call) Run(run func()) *MockVarsManager_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVarsManager_Watch_Call) Return(_a0 <-chan []*transpiler.Vars) *MockVarsManager_Watch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVarsManager_Watch_Call) RunAndReturn(run func() <-chan []*transpiler.Vars) *MockVarsManager_Watch_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockVarsManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockVarsManager creates a new instance of MockVarsManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockVarsManager(t mockConstructorTestingTNewMockVarsManager) *MockVarsManager {
	mock := &MockVarsManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
