// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License 2.0;
// you may not use this file except in compliance with the Elastic License 2.0.

//go:build integration && darwin

package ess

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func makeTestFS(t *testing.T, bytes uint64) string {
	t.Helper()

	size := bytes / (1024 * 1024)
	totalSize := size + uint64(float64(size)*0.025) + 16
	if totalSize > 1024 {
		// hdiutil adds a 128MiB Apple_Free gap to images over 1GiB
		totalSize += 129
	}

	tempDir := t.TempDir()
	imagePath := filepath.Join(tempDir, "disk.dmg")
	mountPoint := filepath.Join(tempDir, "mount")
	require.NoError(t, os.Mkdir(mountPoint, 0o755))
	runHdiutil(t, t.Context(),
		"create",
		"-size", fmt.Sprintf("%dm", totalSize),
		"-fs", "HFS+",
		"-volname", "elastic-agent-diskspace-test",
		imagePath,
	)
	runHdiutil(t, t.Context(),
		"attach",
		"-owners", "on",
		"-nobrowse",
		"-mountpoint", mountPoint,
		imagePath,
	)
	t.Cleanup(func() {
		runHdiutil(t, context.WithoutCancel(t.Context()), "detach", "-force", mountPoint)
	})
	return mountPoint
}

func runHdiutil(t *testing.T, ctx context.Context, args ...string) {
	t.Helper()

	commandContext, cancel := context.WithTimeout(ctx, time.Minute)
	defer cancel()
	command := exec.CommandContext(commandContext, "/usr/bin/hdiutil", args...) // #nosec G204 -- all arguments are fixed or generated by this test
	output, err := command.CombinedOutput()
	require.NoError(t, err, "hdiutil failed: %s", output)
}
