#!/bin/bash

# Required: Upload destination
export BUILDKITE_ARTIFACT_UPLOAD_DESTINATION="gs://buildkite-elastic-agent/$BUILDKITE_PIPELINE_ID/$BUILDKITE_BUILD_ID/$BUILDKITE_JOB_ID"

# Optional: ACL
export BUILDKITE_GS_ACL="private"

# Optional: Authenticated access in UI
export BUILDKITE_GCS_ACCESS_HOST="storage.cloud.google.com"

export BUILDKITE_AGENT_LOG_LEVEL="debug"