name: unit-tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - '8.19'
      - 9.*

permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - macos-15-intel
          - macos-15
          - windows-2022
          - windows-11-arm
        race_detector: [true]
        include:
          - os: ubuntu-22.04
            fips_variant: "requirefips"
            fips_env: "true"
          - os: ubuntu-22.04
            fips_variant: "fips140-only"
            fips_env: "true"
            godebug: "fips140=only,tlsmlkem=0"
          - os: windows-11-arm
            race_detector: false
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          # pkg/testing/tools/git TestGetReleaseBranches test require full git history
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: .go-version

      - name: Install make
        if: runner.os == 'macOS'
        run: |
          brew install make
          export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"

      - name: Install mage
        run: go install github.com/magefile/mage@latest

      - name: mage unitTest
        run: mage unitTest
        env:
          RACE_DETECTOR: ${{ matrix.race_detector }}
          TEST_COVERAGE: true
          FIPS: ${{ matrix.fips_env }}
          GODEBUG: ${{ matrix.godebug }}
