---
name: updatecli-compose

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: read

jobs:
  compose:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

<<<<<<< HEAD
      - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
=======
      - name: Get token
        id: get_token
        uses: elastic/oblt-actions/github/create-token@v1

      - uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
>>>>>>> db0d395b5 (build(deps): bump docker/login-action from 4.4.0 to 4.5.0 (#15774))
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: elastic/oblt-actions/updatecli/run@v1
        with:
          command: --experimental compose diff
          version-file: .updatecli-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: elastic/oblt-actions/updatecli/run@v1
        with:
          command: --experimental compose apply
          version-file: .updatecli-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ failure()  }}
        uses: elastic/oblt-actions/slack/send@v1
        env:
          JOB_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#ingest-notifications"
          message: ":traffic_cone: updatecli failed for `${{ github.repository }}@${{ github.ref_name }}`, `@agent-team` please look what's going on <${{ env.JOB_URL }}|here>"
